#
# ----------------------------
# Database Config's:
# ----------------------------

# This is the database url
database.url = jdbc:postgresql://localhost:5432/aion_ls

# Database user
database.user = aion

# Database password
database.password = aion

# Maximal amount of connections kept in connection pool
database.connectionpool.connections.max = 5

# Maximum wait time when getting a DB connection, before throwing a timeout error
database.connectionpool.timeout = 5000